/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthInput: typeof import('./src/components/Forms/Auth/AuthInput.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Bars: typeof import('./src/components/Icons/Outline/Bars.vue')['default']
    Book: typeof import('./src/components/Icons/Outline/Book.vue')['default']
    Bookmark: typeof import('./src/components/Icons/Outline/Bookmark.vue')['default']
    Email: typeof import('./src/components/Icons/Email.vue')['default']
    Funnel: typeof import('./src/components/Icons/Outline/Funnel.vue')['default']
    GrapeCard: typeof import('./src/components/Grapes/Card/GrapeCard.vue')['default']
    GrapeCardLoading: typeof import('./src/components/Grapes/Card/GrapeCardLoading.vue')['default']
    GrapeSearch: typeof import('./src/components/Grapes/GrapeSearch.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Loading: typeof import('./src/components/Grapes/Card/Loading.vue')['default']
    Login: typeof import('./src/components/Forms/Auth/Login.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Note: typeof import('./src/components/Forms/Note/Note.vue')['default']
    Password: typeof import('./src/components/Icons/Password.vue')['default']
    Register: typeof import('./src/components/Forms/Auth/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Icons/Search.vue')['default']
    Star: typeof import('./src/components/Icons/Outline/Star.vue')['default']
    Swatch: typeof import('./src/components/Icons/Outline/Swatch.vue')['default']
    ToggleConstructorButton: typeof import('./src/components/Grapes/UI/ToggleConstructorButton.vue')['default']
    ToggleFavoriteButton: typeof import('./src/components/Grapes/UI/ToggleFavoriteButton.vue')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
  }
}
