/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    Buttongroup: typeof import('primevue/buttongroup')['default']
    ButtonGroup: typeof import('primevue/buttongroup')['default']
    Card: typeof import('primevue/card')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    GrapeCard: typeof import('./src/components/Grapes/Card/GrapeCard.vue')['default']
    GrapeCardLoading: typeof import('./src/components/Grapes/Card/GrapeCardLoading.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Login: typeof import('./src/components/Forms/Auth/Login.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Password: typeof import('primevue/password')['default']
    Register: typeof import('./src/components/Forms/Auth/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
  }
}
