/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/Dices/': RouteRecordInfo<'/Dices/', '/Dices', Record<never, never>, Record<never, never>>,
    '/Grapes/': RouteRecordInfo<'/Grapes/', '/Grapes', Record<never, never>, Record<never, never>>,
    '/Grapes/[grapeId]': RouteRecordInfo<'/Grapes/[grapeId]', '/Grapes/:grapeId', { grapeId: ParamValue<true> }, { grapeId: ParamValue<false> }>,
    '/Grapes/Constructor': RouteRecordInfo<'/Grapes/Constructor', '/Grapes/Constructor', Record<never, never>, Record<never, never>>,
    '/Grapes/Notes/': RouteRecordInfo<'/Grapes/Notes/', '/Grapes/Notes', Record<never, never>, Record<never, never>>,
    '/Grapes/Notes/[id]': RouteRecordInfo<'/Grapes/Notes/[id]', '/Grapes/Notes/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/User/Login': RouteRecordInfo<'/User/Login', '/User/Login', Record<never, never>, Record<never, never>>,
    '/User/Profile': RouteRecordInfo<'/User/Profile', '/User/Profile', Record<never, never>, Record<never, never>>,
    '/User/Register': RouteRecordInfo<'/User/Register', '/User/Register', Record<never, never>, Record<never, never>>,
  }
}
